// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: deepscan.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileCategory int32

const (
	FileCategory_FILE_CATEGORY_UNSPECIFIED FileCategory = 0
	FileCategory_FILE_CATEGORY_IMAGE       FileCategory = 1
	FileCategory_FILE_CATEGORY_CODE        FileCategory = 2
	FileCategory_FILE_CATEGORY_DOCUMENT    FileCategory = 3
	FileCategory_FILE_CATEGORY_AUDIO       FileCategory = 4
	FileCategory_FILE_CATEGORY_VIDEO       FileCategory = 5
)

// Enum value maps for FileCategory.
var (
	FileCategory_name = map[int32]string{
		0: "FILE_CATEGORY_UNSPECIFIED",
		1: "FILE_CATEGORY_IMAGE",
		2: "FILE_CATEGORY_CODE",
		3: "FILE_CATEGORY_DOCUMENT",
		4: "FILE_CATEGORY_AUDIO",
		5: "FILE_CATEGORY_VIDEO",
	}
	FileCategory_value = map[string]int32{
		"FILE_CATEGORY_UNSPECIFIED": 0,
		"FILE_CATEGORY_IMAGE":       1,
		"FILE_CATEGORY_CODE":        2,
		"FILE_CATEGORY_DOCUMENT":    3,
		"FILE_CATEGORY_AUDIO":       4,
		"FILE_CATEGORY_VIDEO":       5,
	}
)

func (x FileCategory) Enum() *FileCategory {
	p := new(FileCategory)
	*p = x
	return p
}

func (x FileCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_deepscan_proto_enumTypes[0].Descriptor()
}

func (FileCategory) Type() protoreflect.EnumType {
	return &file_deepscan_proto_enumTypes[0]
}

func (x FileCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileCategory.Descriptor instead.
func (FileCategory) EnumDescriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{0}
}

type ChangeKind int32

const (
	ChangeKind_CHANGE_KIND_UNSPECIFIED ChangeKind = 0
	ChangeKind_CHANGE_KIND_CREATED     ChangeKind = 1
	ChangeKind_CHANGE_KIND_MODIFIED    ChangeKind = 2
	ChangeKind_CHANGE_KIND_DELETED     ChangeKind = 3
	ChangeKind_CHANGE_KIND_RENAMED     ChangeKind = 4
)

// Enum value maps for ChangeKind.
var (
	ChangeKind_name = map[int32]string{
		0: "CHANGE_KIND_UNSPECIFIED",
		1: "CHANGE_KIND_CREATED",
		2: "CHANGE_KIND_MODIFIED",
		3: "CHANGE_KIND_DELETED",
		4: "CHANGE_KIND_RENAMED",
	}
	ChangeKind_value = map[string]int32{
		"CHANGE_KIND_UNSPECIFIED": 0,
		"CHANGE_KIND_CREATED":     1,
		"CHANGE_KIND_MODIFIED":    2,
		"CHANGE_KIND_DELETED":     3,
		"CHANGE_KIND_RENAMED":     4,
	}
)

func (x ChangeKind) Enum() *ChangeKind {
	p := new(ChangeKind)
	*p = x
	return p
}

func (x ChangeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_deepscan_proto_enumTypes[1].Descriptor()
}

func (ChangeKind) Type() protoreflect.EnumType {
	return &file_deepscan_proto_enumTypes[1]
}

func (x ChangeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeKind.Descriptor instead.
func (ChangeKind) EnumDescriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{1}
}

type FileRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ModifiedUnixMs int64                  `protobuf:"varint,3,opt,name=modified_unix_ms,json=modifiedUnixMs,proto3" json:"modified_unix_ms,omitempty"`
	Category       FileCategory           `protobuf:"varint,4,opt,name=category,proto3,enum=deepscan.v1.FileCategory" json:"category,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_deepscan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{0}
}

func (x *FileRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileRef) GetModifiedUnixMs() int64 {
	if x != nil {
		return x.ModifiedUnixMs
	}
	return 0
}

func (x *FileRef) GetCategory() FileCategory {
	if x != nil {
		return x.Category
	}
	return FileCategory_FILE_CATEGORY_UNSPECIFIED
}

type FsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ChangeKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=deepscan.v1.ChangeKind" json:"kind,omitempty"`
	File          *FileRef               `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	RenamedFrom   string                 `protobuf:"bytes,3,opt,name=renamed_from,json=renamedFrom,proto3" json:"renamed_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsEvent) Reset() {
	*x = FsEvent{}
	mi := &file_deepscan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsEvent) ProtoMessage() {}

func (x *FsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsEvent.ProtoReflect.Descriptor instead.
func (*FsEvent) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{1}
}

func (x *FsEvent) GetKind() ChangeKind {
	if x != nil {
		return x.Kind
	}
	return ChangeKind_CHANGE_KIND_UNSPECIFIED
}

func (x *FsEvent) GetFile() *FileRef {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FsEvent) GetRenamedFrom() string {
	if x != nil {
		return x.RenamedFrom
	}
	return ""
}

type IndexAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexAck) Reset() {
	*x = IndexAck{}
	mi := &file_deepscan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexAck) ProtoMessage() {}

func (x *IndexAck) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexAck.ProtoReflect.Descriptor instead.
func (*IndexAck) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{2}
}

func (x *IndexAck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IndexAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IndexAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IndexPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootPath      string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexPathRequest) Reset() {
	*x = IndexPathRequest{}
	mi := &file_deepscan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexPathRequest) ProtoMessage() {}

func (x *IndexPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexPathRequest.ProtoReflect.Descriptor instead.
func (*IndexPathRequest) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{3}
}

func (x *IndexPathRequest) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *IndexPathRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type IndexProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesScanned  int64                  `protobuf:"varint,1,opt,name=files_scanned,json=filesScanned,proto3" json:"files_scanned,omitempty"`
	FilesIndexed  int64                  `protobuf:"varint,2,opt,name=files_indexed,json=filesIndexed,proto3" json:"files_indexed,omitempty"`
	FilesSkipped  int64                  `protobuf:"varint,3,opt,name=files_skipped,json=filesSkipped,proto3" json:"files_skipped,omitempty"`
	CurrentPath   string                 `protobuf:"bytes,4,opt,name=current_path,json=currentPath,proto3" json:"current_path,omitempty"`
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexProgress) Reset() {
	*x = IndexProgress{}
	mi := &file_deepscan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexProgress) ProtoMessage() {}

func (x *IndexProgress) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexProgress.ProtoReflect.Descriptor instead.
func (*IndexProgress) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{4}
}

func (x *IndexProgress) GetFilesScanned() int64 {
	if x != nil {
		return x.FilesScanned
	}
	return 0
}

func (x *IndexProgress) GetFilesIndexed() int64 {
	if x != nil {
		return x.FilesIndexed
	}
	return 0
}

func (x *IndexProgress) GetFilesSkipped() int64 {
	if x != nil {
		return x.FilesSkipped
	}
	return 0
}

func (x *IndexProgress) GetCurrentPath() string {
	if x != nil {
		return x.CurrentPath
	}
	return ""
}

func (x *IndexProgress) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type IndexStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DbHealthy         bool                   `protobuf:"varint,1,opt,name=db_healthy,json=dbHealthy,proto3" json:"db_healthy,omitempty"`
	TotalIndexedFiles int64                  `protobuf:"varint,2,opt,name=total_indexed_files,json=totalIndexedFiles,proto3" json:"total_indexed_files,omitempty"`
	PendingQueueDepth int64                  `protobuf:"varint,3,opt,name=pending_queue_depth,json=pendingQueueDepth,proto3" json:"pending_queue_depth,omitempty"`
	IsScanning        bool                   `protobuf:"varint,4,opt,name=is_scanning,json=isScanning,proto3" json:"is_scanning,omitempty"`
	LastError         string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IndexStatus) Reset() {
	*x = IndexStatus{}
	mi := &file_deepscan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexStatus) ProtoMessage() {}

func (x *IndexStatus) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexStatus.ProtoReflect.Descriptor instead.
func (*IndexStatus) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{5}
}

func (x *IndexStatus) GetDbHealthy() bool {
	if x != nil {
		return x.DbHealthy
	}
	return false
}

func (x *IndexStatus) GetTotalIndexedFiles() int64 {
	if x != nil {
		return x.TotalIndexedFiles
	}
	return 0
}

func (x *IndexStatus) GetPendingQueueDepth() int64 {
	if x != nil {
		return x.PendingQueueDepth
	}
	return 0
}

func (x *IndexStatus) GetIsScanning() bool {
	if x != nil {
		return x.IsScanning
	}
	return false
}

func (x *IndexStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Query:
	//
	//	*SearchRequest_TextQuery
	//	*SearchRequest_ImageQueryBytes
	Query         isSearchRequest_Query `protobuf_oneof:"query"`
	Scope         []FileCategory        `protobuf:"varint,3,rep,packed,name=scope,proto3,enum=deepscan.v1.FileCategory" json:"scope,omitempty"`
	TopK          int32                 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_deepscan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQuery() isSearchRequest_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetTextQuery() string {
	if x != nil {
		if x, ok := x.Query.(*SearchRequest_TextQuery); ok {
			return x.TextQuery
		}
	}
	return ""
}

func (x *SearchRequest) GetImageQueryBytes() []byte {
	if x != nil {
		if x, ok := x.Query.(*SearchRequest_ImageQueryBytes); ok {
			return x.ImageQueryBytes
		}
	}
	return nil
}

func (x *SearchRequest) GetScope() []FileCategory {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type isSearchRequest_Query interface {
	isSearchRequest_Query()
}

type SearchRequest_TextQuery struct {
	TextQuery string `protobuf:"bytes,1,opt,name=text_query,json=textQuery,proto3,oneof"`
}

type SearchRequest_ImageQueryBytes struct {
	ImageQueryBytes []byte `protobuf:"bytes,2,opt,name=image_query_bytes,json=imageQueryBytes,proto3,oneof"`
}

func (*SearchRequest_TextQuery) isSearchRequest_Query() {}

func (*SearchRequest_ImageQueryBytes) isSearchRequest_Query() {}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileRef               `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_deepscan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResult) GetFile() *FileRef {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	QueryTimeMs   int64                  `protobuf:"varint,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_deepscan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetQueryTimeMs() int64 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

type RevealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealRequest) Reset() {
	*x = RevealRequest{}
	mi := &file_deepscan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealRequest) ProtoMessage() {}

func (x *RevealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealRequest.ProtoReflect.Descriptor instead.
func (*RevealRequest) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{9}
}

func (x *RevealRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RevealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealResponse) Reset() {
	*x = RevealResponse{}
	mi := &file_deepscan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealResponse) ProtoMessage() {}

func (x *RevealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealResponse.ProtoReflect.Descriptor instead.
func (*RevealResponse) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{10}
}

func (x *RevealResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevealResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MimeHint      string                 `protobuf:"bytes,2,opt,name=mime_hint,json=mimeHint,proto3" json:"mime_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_deepscan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{11}
}

func (x *ExtractRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExtractRequest) GetMimeHint() string {
	if x != nil {
		return x.MimeHint
	}
	return ""
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtractedText string                 `protobuf:"bytes,1,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OcrUsed       bool                   `protobuf:"varint,3,opt,name=ocr_used,json=ocrUsed,proto3" json:"ocr_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_deepscan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{12}
}

func (x *ExtractResponse) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

func (x *ExtractResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExtractResponse) GetOcrUsed() bool {
	if x != nil {
		return x.OcrUsed
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_deepscan_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_deepscan_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_deepscan_proto_rawDescGZIP(), []int{13}
}

var File_deepscan_proto protoreflect.FileDescriptor

const file_deepscan_proto_rawDesc = "" +
	"\n" +
	"\x0edeepscan.proto\x12\vdeepscan.v1\"\x9d\x01\n" +
	"\aFileRef\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12(\n" +
	"\x10modified_unix_ms\x18\x03 \x01(\x03R\x0emodifiedUnixMs\x125\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x19.deepscan.v1.FileCategoryR\bcategory\"\x83\x01\n" +
	"\aFsEvent\x12+\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x17.deepscan.v1.ChangeKindR\x04kind\x12(\n" +
	"\x04file\x18\x02 \x01(\v2\x14.deepscan.v1.FileRefR\x04file\x12!\n" +
	"\frenamed_from\x18\x03 \x01(\tR\vrenamedFrom\"P\n" +
	"\bIndexAck\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"M\n" +
	"\x10IndexPathRequest\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\xb5\x01\n" +
	"\rIndexProgress\x12#\n" +
	"\rfiles_scanned\x18\x01 \x01(\x03R\ffilesScanned\x12#\n" +
	"\rfiles_indexed\x18\x02 \x01(\x03R\ffilesIndexed\x12#\n" +
	"\rfiles_skipped\x18\x03 \x01(\x03R\ffilesSkipped\x12!\n" +
	"\fcurrent_path\x18\x04 \x01(\tR\vcurrentPath\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\"\xcc\x01\n" +
	"\vIndexStatus\x12\x1d\n" +
	"\n" +
	"db_healthy\x18\x01 \x01(\bR\tdbHealthy\x12.\n" +
	"\x13total_indexed_files\x18\x02 \x01(\x03R\x11totalIndexedFiles\x12.\n" +
	"\x13pending_queue_depth\x18\x03 \x01(\x03R\x11pendingQueueDepth\x12\x1f\n" +
	"\vis_scanning\x18\x04 \x01(\bR\n" +
	"isScanning\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\"\xad\x01\n" +
	"\rSearchRequest\x12\x1f\n" +
	"\n" +
	"text_query\x18\x01 \x01(\tH\x00R\ttextQuery\x12,\n" +
	"\x11image_query_bytes\x18\x02 \x01(\fH\x00R\x0fimageQueryBytes\x12/\n" +
	"\x05scope\x18\x03 \x03(\x0e2\x19.deepscan.v1.FileCategoryR\x05scope\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topKB\a\n" +
	"\x05query\"h\n" +
	"\fSearchResult\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.deepscan.v1.FileRefR\x04file\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\"i\n" +
	"\x0eSearchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.deepscan.v1.SearchResultR\aresults\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x03R\vqueryTimeMs\"#\n" +
	"\rRevealRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"@\n" +
	"\x0eRevealResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"A\n" +
	"\x0eExtractRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tmime_hint\x18\x02 \x01(\tR\bmimeHint\"\xd8\x01\n" +
	"\x0fExtractResponse\x12%\n" +
	"\x0eextracted_text\x18\x01 \x01(\tR\rextractedText\x12F\n" +
	"\bmetadata\x18\x02 \x03(\v2*.deepscan.v1.ExtractResponse.MetadataEntryR\bmetadata\x12\x19\n" +
	"\bocr_used\x18\x03 \x01(\bR\aocrUsed\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\a\n" +
	"\x05Empty*\xac\x01\n" +
	"\fFileCategory\x12\x1d\n" +
	"\x19FILE_CATEGORY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FILE_CATEGORY_IMAGE\x10\x01\x12\x16\n" +
	"\x12FILE_CATEGORY_CODE\x10\x02\x12\x1a\n" +
	"\x16FILE_CATEGORY_DOCUMENT\x10\x03\x12\x17\n" +
	"\x13FILE_CATEGORY_AUDIO\x10\x04\x12\x17\n" +
	"\x13FILE_CATEGORY_VIDEO\x10\x05*\x8e\x01\n" +
	"\n" +
	"ChangeKind\x12\x1b\n" +
	"\x17CHANGE_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CHANGE_KIND_CREATED\x10\x01\x12\x18\n" +
	"\x14CHANGE_KIND_MODIFIED\x10\x02\x12\x17\n" +
	"\x13CHANGE_KIND_DELETED\x10\x03\x12\x17\n" +
	"\x13CHANGE_KIND_RENAMED\x10\x042\xd8\x01\n" +
	"\fIndexService\x12>\n" +
	"\vWatchEvents\x12\x14.deepscan.v1.FsEvent\x1a\x15.deepscan.v1.IndexAck(\x010\x01\x12H\n" +
	"\tIndexPath\x12\x1d.deepscan.v1.IndexPathRequest\x1a\x1a.deepscan.v1.IndexProgress0\x01\x12>\n" +
	"\x0eGetIndexStatus\x12\x12.deepscan.v1.Empty\x1a\x18.deepscan.v1.IndexStatus2\x99\x01\n" +
	"\rSearchService\x12A\n" +
	"\x06Search\x12\x1a.deepscan.v1.SearchRequest\x1a\x1b.deepscan.v1.SearchResponse\x12E\n" +
	"\n" +
	"RevealInOs\x12\x1a.deepscan.v1.RevealRequest\x1a\x1b.deepscan.v1.RevealResponse2c\n" +
	"\x13ParserBridgeService\x12L\n" +
	"\x0fExtractDocument\x12\x1b.deepscan.v1.ExtractRequest\x1a\x1c.deepscan.v1.ExtractResponseBJ\n" +
	"\x16com.deepscan.parser.pbP\x01Z.github.com/izaan-cell/DeepScan/go-daemon/pb;pbb\x06proto3"

var (
	file_deepscan_proto_rawDescOnce sync.Once
	file_deepscan_proto_rawDescData []byte
)

func file_deepscan_proto_rawDescGZIP() []byte {
	file_deepscan_proto_rawDescOnce.Do(func() {
		file_deepscan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deepscan_proto_rawDesc), len(file_deepscan_proto_rawDesc)))
	})
	return file_deepscan_proto_rawDescData
}

var file_deepscan_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_deepscan_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_deepscan_proto_goTypes = []any{
	(FileCategory)(0),        // 0: deepscan.v1.FileCategory
	(ChangeKind)(0),          // 1: deepscan.v1.ChangeKind
	(*FileRef)(nil),          // 2: deepscan.v1.FileRef
	(*FsEvent)(nil),          // 3: deepscan.v1.FsEvent
	(*IndexAck)(nil),         // 4: deepscan.v1.IndexAck
	(*IndexPathRequest)(nil), // 5: deepscan.v1.IndexPathRequest
	(*IndexProgress)(nil),    // 6: deepscan.v1.IndexProgress
	(*IndexStatus)(nil),      // 7: deepscan.v1.IndexStatus
	(*SearchRequest)(nil),    // 8: deepscan.v1.SearchRequest
	(*SearchResult)(nil),     // 9: deepscan.v1.SearchResult
	(*SearchResponse)(nil),   // 10: deepscan.v1.SearchResponse
	(*RevealRequest)(nil),    // 11: deepscan.v1.RevealRequest
	(*RevealResponse)(nil),   // 12: deepscan.v1.RevealResponse
	(*ExtractRequest)(nil),   // 13: deepscan.v1.ExtractRequest
	(*ExtractResponse)(nil),  // 14: deepscan.v1.ExtractResponse
	(*Empty)(nil),            // 15: deepscan.v1.Empty
	nil,                      // 16: deepscan.v1.ExtractResponse.MetadataEntry
}
var file_deepscan_proto_depIdxs = []int32{
	0,  // 0: deepscan.v1.FileRef.category:type_name -> deepscan.v1.FileCategory
	1,  // 1: deepscan.v1.FsEvent.kind:type_name -> deepscan.v1.ChangeKind
	2,  // 2: deepscan.v1.FsEvent.file:type_name -> deepscan.v1.FileRef
	0,  // 3: deepscan.v1.SearchRequest.scope:type_name -> deepscan.v1.FileCategory
	2,  // 4: deepscan.v1.SearchResult.file:type_name -> deepscan.v1.FileRef
	9,  // 5: deepscan.v1.SearchResponse.results:type_name -> deepscan.v1.SearchResult
	16, // 6: deepscan.v1.ExtractResponse.metadata:type_name -> deepscan.v1.ExtractResponse.MetadataEntry
	3,  // 7: deepscan.v1.IndexService.WatchEvents:input_type -> deepscan.v1.FsEvent
	5,  // 8: deepscan.v1.IndexService.IndexPath:input_type -> deepscan.v1.IndexPathRequest
	15, // 9: deepscan.v1.IndexService.GetIndexStatus:input_type -> deepscan.v1.Empty
	8,  // 10: deepscan.v1.SearchService.Search:input_type -> deepscan.v1.SearchRequest
	11, // 11: deepscan.v1.SearchService.RevealInOs:input_type -> deepscan.v1.RevealRequest
	13, // 12: deepscan.v1.ParserBridgeService.ExtractDocument:input_type -> deepscan.v1.ExtractRequest
	4,  // 13: deepscan.v1.IndexService.WatchEvents:output_type -> deepscan.v1.IndexAck
	6,  // 14: deepscan.v1.IndexService.IndexPath:output_type -> deepscan.v1.IndexProgress
	7,  // 15: deepscan.v1.IndexService.GetIndexStatus:output_type -> deepscan.v1.IndexStatus
	10, // 16: deepscan.v1.SearchService.Search:output_type -> deepscan.v1.SearchResponse
	12, // 17: deepscan.v1.SearchService.RevealInOs:output_type -> deepscan.v1.RevealResponse
	14, // 18: deepscan.v1.ParserBridgeService.ExtractDocument:output_type -> deepscan.v1.ExtractResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_deepscan_proto_init() }
func file_deepscan_proto_init() {
	if File_deepscan_proto != nil {
		return
	}
	file_deepscan_proto_msgTypes[6].OneofWrappers = []any{
		(*SearchRequest_TextQuery)(nil),
		(*SearchRequest_ImageQueryBytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deepscan_proto_rawDesc), len(file_deepscan_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_deepscan_proto_goTypes,
		DependencyIndexes: file_deepscan_proto_depIdxs,
		EnumInfos:         file_deepscan_proto_enumTypes,
		MessageInfos:      file_deepscan_proto_msgTypes,
	}.Build()
	File_deepscan_proto = out.File
	file_deepscan_proto_goTypes = nil
	file_deepscan_proto_depIdxs = nil
}
