// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: deepscan.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexService_WatchEvents_FullMethodName    = "/deepscan.v1.IndexService/WatchEvents"
	IndexService_IndexPath_FullMethodName      = "/deepscan.v1.IndexService/IndexPath"
	IndexService_GetIndexStatus_FullMethodName = "/deepscan.v1.IndexService/GetIndexStatus"
)

// IndexServiceClient is the client API for IndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexServiceClient interface {
	WatchEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FsEvent, IndexAck], error)
	IndexPath(ctx context.Context, in *IndexPathRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexProgress], error)
	GetIndexStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IndexStatus, error)
}

type indexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexServiceClient(cc grpc.ClientConnInterface) IndexServiceClient {
	return &indexServiceClient{cc}
}

func (c *indexServiceClient) WatchEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FsEvent, IndexAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IndexService_ServiceDesc.Streams[0], IndexService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FsEvent, IndexAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexService_WatchEventsClient = grpc.BidiStreamingClient[FsEvent, IndexAck]

func (c *indexServiceClient) IndexPath(ctx context.Context, in *IndexPathRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IndexService_ServiceDesc.Streams[1], IndexService_IndexPath_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IndexPathRequest, IndexProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexService_IndexPathClient = grpc.ServerStreamingClient[IndexProgress]

func (c *indexServiceClient) GetIndexStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IndexStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexStatus)
	err := c.cc.Invoke(ctx, IndexService_GetIndexStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexServiceServer is the server API for IndexService service.
// All implementations must embed UnimplementedIndexServiceServer
// for forward compatibility.
type IndexServiceServer interface {
	WatchEvents(grpc.BidiStreamingServer[FsEvent, IndexAck]) error
	IndexPath(*IndexPathRequest, grpc.ServerStreamingServer[IndexProgress]) error
	GetIndexStatus(context.Context, *Empty) (*IndexStatus, error)
	mustEmbedUnimplementedIndexServiceServer()
}

// UnimplementedIndexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexServiceServer struct{}

func (UnimplementedIndexServiceServer) WatchEvents(grpc.BidiStreamingServer[FsEvent, IndexAck]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedIndexServiceServer) IndexPath(*IndexPathRequest, grpc.ServerStreamingServer[IndexProgress]) error {
	return status.Error(codes.Unimplemented, "method IndexPath not implemented")
}
func (UnimplementedIndexServiceServer) GetIndexStatus(context.Context, *Empty) (*IndexStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndexStatus not implemented")
}
func (UnimplementedIndexServiceServer) mustEmbedUnimplementedIndexServiceServer() {}
func (UnimplementedIndexServiceServer) testEmbeddedByValue()                      {}

// UnsafeIndexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexServiceServer will
// result in compilation errors.
type UnsafeIndexServiceServer interface {
	mustEmbedUnimplementedIndexServiceServer()
}

func RegisterIndexServiceServer(s grpc.ServiceRegistrar, srv IndexServiceServer) {
	// If the following call panics, it indicates UnimplementedIndexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexService_ServiceDesc, srv)
}

func _IndexService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexServiceServer).WatchEvents(&grpc.GenericServerStream[FsEvent, IndexAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexService_WatchEventsServer = grpc.BidiStreamingServer[FsEvent, IndexAck]

func _IndexService_IndexPath_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IndexPathRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IndexServiceServer).IndexPath(m, &grpc.GenericServerStream[IndexPathRequest, IndexProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexService_IndexPathServer = grpc.ServerStreamingServer[IndexProgress]

func _IndexService_GetIndexStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).GetIndexStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexService_GetIndexStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).GetIndexStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexService_ServiceDesc is the grpc.ServiceDesc for IndexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepscan.v1.IndexService",
	HandlerType: (*IndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndexStatus",
			Handler:    _IndexService_GetIndexStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _IndexService_WatchEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "IndexPath",
			Handler:       _IndexService_IndexPath_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deepscan.proto",
}

const (
	SearchService_Search_FullMethodName     = "/deepscan.v1.SearchService/Search"
	SearchService_RevealInOs_FullMethodName = "/deepscan.v1.SearchService/RevealInOs"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	RevealInOs(ctx context.Context, in *RevealRequest, opts ...grpc.CallOption) (*RevealResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SearchService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) RevealInOs(ctx context.Context, in *RevealRequest, opts ...grpc.CallOption) (*RevealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevealResponse)
	err := c.cc.Invoke(ctx, SearchService_RevealInOs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	RevealInOs(context.Context, *RevealRequest) (*RevealResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchServiceServer) RevealInOs(context.Context, *RevealRequest) (*RevealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevealInOs not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_RevealInOs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).RevealInOs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_RevealInOs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).RevealInOs(ctx, req.(*RevealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepscan.v1.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
		{
			MethodName: "RevealInOs",
			Handler:    _SearchService_RevealInOs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deepscan.proto",
}

const (
	ParserBridgeService_ExtractDocument_FullMethodName = "/deepscan.v1.ParserBridgeService/ExtractDocument"
)

// ParserBridgeServiceClient is the client API for ParserBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParserBridgeServiceClient interface {
	ExtractDocument(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type parserBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParserBridgeServiceClient(cc grpc.ClientConnInterface) ParserBridgeServiceClient {
	return &parserBridgeServiceClient{cc}
}

func (c *parserBridgeServiceClient) ExtractDocument(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, ParserBridgeService_ExtractDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParserBridgeServiceServer is the server API for ParserBridgeService service.
// All implementations must embed UnimplementedParserBridgeServiceServer
// for forward compatibility.
type ParserBridgeServiceServer interface {
	ExtractDocument(context.Context, *ExtractRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedParserBridgeServiceServer()
}

// UnimplementedParserBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParserBridgeServiceServer struct{}

func (UnimplementedParserBridgeServiceServer) ExtractDocument(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractDocument not implemented")
}
func (UnimplementedParserBridgeServiceServer) mustEmbedUnimplementedParserBridgeServiceServer() {}
func (UnimplementedParserBridgeServiceServer) testEmbeddedByValue()                             {}

// UnsafeParserBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParserBridgeServiceServer will
// result in compilation errors.
type UnsafeParserBridgeServiceServer interface {
	mustEmbedUnimplementedParserBridgeServiceServer()
}

func RegisterParserBridgeServiceServer(s grpc.ServiceRegistrar, srv ParserBridgeServiceServer) {
	// If the following call panics, it indicates UnimplementedParserBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParserBridgeService_ServiceDesc, srv)
}

func _ParserBridgeService_ExtractDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserBridgeServiceServer).ExtractDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserBridgeService_ExtractDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserBridgeServiceServer).ExtractDocument(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParserBridgeService_ServiceDesc is the grpc.ServiceDesc for ParserBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParserBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deepscan.v1.ParserBridgeService",
	HandlerType: (*ParserBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractDocument",
			Handler:    _ParserBridgeService_ExtractDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deepscan.proto",
}
